{% set name = "extension-helpers" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 78d04185f196e3e0bc5fd8418ce298b014c46f7ac609f6a8c10bf70e8c978324

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=43.0.0
    - setuptools-scm >=6.2
  run:
    - python
    - setuptools >=64
    - tomli >=1.0.0  # [py<311]


{% set deselect_tests = "" %}
{% set deselect_tests = deselect_tests + "--deselect=test_setup_helpers.py::test_no_setup_py" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test_setup_helpers.py::test_only_pyproject" %}  # [win]

test:
  imports:
    - extension_helpers
  requires:
    - pip
    - pytest
    - cython
    - python-build
    - wheel
  commands:
    - pip check
    - set CL=/O2 /GL-  # [win]
    - set LINK=/INCREMENTAL:NO /LTCG:OFF  # [win]
    - pytest -vv --pyargs extension_helpers.tests

about:
  home: https://github.com/astropy/extension-helpers
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Utilities for building and installing packages with compiled extensions
  description: |
    "The extension-helpers package includes convenience helpers to assist
    with building Python packages with compiled C/Cython extensions."
  doc_url: https://extension-helpers.readthedocs.io
  dev_url: https://github.com/astropy/extension-helpers

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - mwcraig
    - bsipocz
