{% set name = "extension-helpers" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f95dd304a523d4ff6680d9504fa1d68a4dd03bf3bfbbe0ade4d927ed9e693f00

build:
  skip: True  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools 43.0.0
    - setuptools_scm 6.2
  run:
    - python
    - setuptools >=40.2
    - tomli >=1.0.0  # [py<311]

test:
  imports:
    - extension_helpers
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/astropy/extension-helpers
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Utilities for building and installing packages with compiled extensions'
  description: |
    "The extension-helpers package includes convenience helpers to assist
    with building Python packages with compiled C/Cython extensions."
  doc_url: https://extension-helpers.readthedocs.io/
  dev_url: https://github.com/astropy/extension-helpers

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - mwcraig
    - bsipocz
